# Generated by Django 4.2.29 on 2026-07-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_contactmessage_event_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/articles/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/events/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="Image URL"),
        ),
        migrations.AlterField(
            model_name="event",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="Image URL"),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="app.category",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="app.category",
                verbose_name="Catégorie",
            ),
        ),
    ]
