# Generated by Django 4.2.29 on 2026-07-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_category_article_image_event_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_key",
                    models.CharField(
                        choices=[
                            ("home", "Accueil"),
                            ("about", "À propos"),
                            ("gallery", "Galerie"),
                            ("contact", "Contact"),
                        ],
                        max_length=50,
                        verbose_name="Page",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Sous-titre"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Contenu")),
                ("image_url", models.URLField(blank=True, verbose_name="Image URL")),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Texte du bouton"
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Lien du bouton"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Section de page",
                "verbose_name_plural": "Sections de page",
                "ordering": ["order", "title"],
            },
        ),
    ]
