# Generated by Django 4.2.29 on 2026-07-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0004_pagesection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Father",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Nom complet"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Titre / fonction"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/fathers/",
                        verbose_name="Photo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="father_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Père",
                "verbose_name_plural": "Pères",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Homily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "gospel",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Évangile"
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("homelie", "Homélie"),
                            ("meditation", "Méditation"),
                            ("conference", "Conférence"),
                        ],
                        default="homelie",
                        max_length=50,
                        verbose_name="Genre",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Texte")),
                ("audio_url", models.URLField(blank=True, verbose_name="Audio URL")),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/homilies/audio/",
                        verbose_name="Fichier audio",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/homilies/pdf/",
                        verbose_name="PDF",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homilies",
                        to="app.father",
                        verbose_name="Père",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homélie",
                "verbose_name_plural": "Homélies",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
