# Generated by Django 4.2.29 on 2026-07-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_father_homily"),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("conference", "Conférence"),
                            ("seminaire", "Séminaire"),
                            ("atelier", "Atelier"),
                            ("formation", "Formation"),
                            ("autre", "Autre"),
                        ],
                        default="formation",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                ("summary", models.TextField(verbose_name="Résumé")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "duration",
                    models.CharField(blank=True, max_length=100, verbose_name="Durée"),
                ),
                (
                    "capacity",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Capacité / public"
                    ),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="Image URL")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/trainings/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
                "ordering": ["start_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="TrainingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre de l’étape"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="app.training",
                        verbose_name="Formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de formation",
                "verbose_name_plural": "Étapes de formation",
                "ordering": ["order", "title"],
            },
        ),
    ]
