# Generated by Django 4.2.29 on 2026-07-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_training_trainingstep"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiritualResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("meditation", "Méditation"),
                            ("reflection", "Réflexion"),
                            ("prayer", "Prière"),
                            ("guide", "Guide"),
                            ("other", "Autre"),
                        ],
                        default="meditation",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                ("summary", models.TextField(verbose_name="Résumé")),
                ("content", models.TextField(blank=True, verbose_name="Contenu")),
                (
                    "author",
                    models.CharField(blank=True, max_length=150, verbose_name="Auteur"),
                ),
                ("audio_url", models.URLField(blank=True, verbose_name="Audio URL")),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/resources/pdf/",
                        verbose_name="PDF",
                    ),
                ),
                ("image_url", models.URLField(blank=True, verbose_name="Image URL")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/resources/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ressource spirituelle",
                "verbose_name_plural": "Ressources spirituelles",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
