# Generated by Django 4.2.29 on 2026-07-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_spiritualresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Icône (emoji)"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                ("text", models.TextField(verbose_name="Texte")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Instruction d'accès",
                "verbose_name_plural": "Instructions d'accès",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="BibleQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=250, verbose_name="Question")),
                (
                    "questioner_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Nom du/de la questionneur(se)",
                    ),
                ),
                (
                    "questioner_context",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Contexte (service, situation...)",
                    ),
                ),
                ("answer", models.TextField(verbose_name="Réponse")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("souffrance", "Souffrance & Providence"),
                            ("priere", "Prière & Spiritualité"),
                            ("vie_eternelle", "Vie après la mort"),
                            ("sacrements", "Sacrements"),
                            ("ethique", "Éthique & Morale"),
                            ("famille", "Famille & Relations"),
                        ],
                        default="priere",
                        max_length=30,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bible_answers",
                        to="app.father",
                        verbose_name="Répondant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question biblique",
                "verbose_name_plural": "Questions bibliques",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BibleVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verse_type",
                    models.CharField(
                        choices=[("daily", "Verset du jour"), ("psalm", "Psaume")],
                        default="daily",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "reference",
                    models.CharField(max_length=100, verbose_name="Référence"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=150, verbose_name="Titre"),
                ),
                ("context", models.TextField(blank=True, verbose_name="Contexte")),
                ("quote", models.TextField(verbose_name="Texte")),
                (
                    "tag_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Étiquette"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Verset biblique",
                "verbose_name_plural": "Versets bibliques",
                "ordering": ["verse_type", "order", "reference"],
            },
        ),
        migrations.CreateModel(
            name="ContactChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        help_text="Identifie le bloc de la page qui affiche cette carte (ex. services_urgence).",
                        max_length=50,
                        verbose_name="Section",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "extension",
                    models.CharField(blank=True, max_length=20, verbose_name="Poste"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=250, verbose_name="Note"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Carte de contact",
                "verbose_name_plural": "Cartes de contact",
                "ordering": ["section_key", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Titre")),
                ("url", models.URLField(verbose_name="Lien")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Description"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Lien externe",
                "verbose_name_plural": "Liens externes",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="LiturgicalSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Titre")),
                (
                    "period_label",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Période"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Temps liturgique fort",
                "verbose_name_plural": "Temps liturgiques forts",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="MeditationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Titre")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("method", "Méthode de méditation"),
                            ("silence", "Temps de silence"),
                        ],
                        default="method",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "duration_label",
                    models.CharField(blank=True, max_length=50, verbose_name="Durée"),
                ),
                (
                    "tip",
                    models.TextField(
                        blank=True, verbose_name="Conseil (« Pour débuter »)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Méthode / temps de méditation",
                "verbose_name_plural": "Méthodes / temps de méditation",
                "ordering": ["category", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="RecurringActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Icône (emoji)"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Titre")),
                (
                    "schedule_label",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Horaire"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=150, verbose_name="Lieu"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Activité régulière",
                "verbose_name_plural": "Activités régulières",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True, verbose_name="Clé")),
                ("title", models.CharField(max_length=150, verbose_name="Titre")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Horaire",
                "verbose_name_plural": "Horaires",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Icône (emoji)"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Texte du lien"
                    ),
                ),
                (
                    "link_url",
                    models.CharField(blank=True, max_length=250, verbose_name="Lien"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
            ],
            options={
                "verbose_name": "Service proposé",
                "verbose_name_plural": "Services proposés",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Nom complet"),
                ),
                (
                    "role_title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Fonction"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("father", "Père"),
                            ("sister", "Sœur"),
                            ("staff", "Employé"),
                            ("volunteer", "Bénévole"),
                        ],
                        default="staff",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="uploads/team/",
                        verbose_name="Photo",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
                "ordering": ["order", "full_name"],
            },
        ),
        migrations.AddField(
            model_name="homily",
            name="duration_label",
            field=models.CharField(blank=True, max_length=50, verbose_name="Durée"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="emergency_note",
            field=models.TextField(blank=True, verbose_name="Note d'urgence"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="emergency_phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Téléphone d'urgence"
            ),
        ),
        migrations.AddField(
            model_name="spiritualresource",
            name="external_url",
            field=models.URLField(
                blank=True, verbose_name="Lien externe (app, site...)"
            ),
        ),
        migrations.AddField(
            model_name="spiritualresource",
            name="file_size_label",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Taille du fichier"
            ),
        ),
        migrations.AddField(
            model_name="training",
            name="speaker",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Intervenant"
            ),
        ),
        migrations.AddField(
            model_name="trainingstep",
            name="duration_label",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Durée / détail"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="type",
            field=models.CharField(
                choices=[
                    ("conference", "Conférence"),
                    ("seminaire", "Séminaire"),
                    ("atelier", "Atelier"),
                    ("formation", "Formation"),
                    ("session_info", "Session d'information"),
                    ("autre", "Autre"),
                ],
                default="formation",
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.CreateModel(
            name="ServiceOfferingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Texte")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app.serviceoffering",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail de service",
                "verbose_name_plural": "Détails de service",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_label", models.CharField(max_length=100, verbose_name="Jour(s)")),
                (
                    "time_label",
                    models.CharField(max_length=100, verbose_name="Plage horaire"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="app.schedule",
                        verbose_name="Horaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Créneau",
                "verbose_name_plural": "Créneaux",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PageSectionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="app.pagesection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pastille de section",
                "verbose_name_plural": "Pastilles de section",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="MeditationMethodStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Texte")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="app.meditationmethod",
                        verbose_name="Méthode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de méditation",
                "verbose_name_plural": "Étapes de méditation",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LiturgicalSeasonItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Texte")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app.liturgicalseason",
                        verbose_name="Temps liturgique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail de temps liturgique",
                "verbose_name_plural": "Détails de temps liturgique",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BibleQuestionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Référence")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="app.biblequestion",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Référence biblique",
                "verbose_name_plural": "Références bibliques",
                "ordering": ["order", "id"],
            },
        ),
    ]
