# Generated by Django 4.2.29 on 2026-07-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_accessinstruction_biblequestion_bibleverse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagesection",
            name="page_key",
            field=models.CharField(
                choices=[
                    ("home", "Accueil"),
                    ("about", "À propos"),
                    ("gallery", "Galerie"),
                    ("contact", "Contact"),
                    ("formations", "Formations"),
                ],
                max_length=50,
                verbose_name="Page",
            ),
        ),
    ]
