# Generated by Django 4.2.29 on 2026-07-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_pagesection_page_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "cover_image_url",
                    models.URLField(blank=True, verbose_name="Image de couverture"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Album photo",
                "verbose_name_plural": "Albums photo",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=200, verbose_name="Compétence acquise"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="app.training",
                        verbose_name="Formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence de formation",
                "verbose_name_plural": "Compétences de formation",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="app.galleryalbum",
                verbose_name="Album",
            ),
        ),
    ]
