# Generated by Django 4.2.29 on 2026-07-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_galleryalbum_trainingskill_galleryimage_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryalbum",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/gallery_albums/",
                verbose_name="Image de couverture",
            ),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/gallery_images/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/hero_slides/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="pagesection",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/page_sections/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="galleryalbum",
            name="cover_image_url",
            field=models.URLField(blank=True, verbose_name="Image de couverture URL"),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="Image URL"),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="Image URL"),
        ),
    ]
